### ISSUE TITLE
shape vector是什么啊

### ISSUE THREAD

**Issue by justinluyao** [ziyeshanwai/MANO_LAYER_NUMPY#1]
这里的shape vector是什么 怎么得到啊 还有就是输入的pose是15个点 输出的pose是21个点，这里边的点是重复的吗？还是完全不同的两组点

**Comment by ziyeshanwai** [comment]
@justinluyao 建议你多读读论文，shape vector大概是控制手的形状的，比如大小，胖瘦，但是不会改变手的姿态，是通过类似PCA的方式得到的。输出的pose里面应该有根节点的旋转平移信息吧，记不清了，你可以下载代码，改下输入的参数可视化的看下，这样更加直观
